spring.application.name=portfolio
#**********************************************************

server.port=3003
logging.file.name=log/mylog.log

spring.datasource.url=jdbc:postgresql://localhost:5432/PortfolioDB
spring.datasource.username=postgres
spring.datasource.password=YourStrong@Passw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional settings
spring.jpa.show-sql=true


#update: Hibernate will attempt to automatically create missing tables and columns based on your entity classes.
#create: Hibernate will drop and recreate the schema every time the application starts (use this with caution in production)
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=update


#**********************************************************







